### ISSUE TITLE
Molsimplify crashing on clicking "Draw Ligands"

### ISSUE THREAD

**Issue by Alan-Rusty24** [hjkgrp/molSimplify#14] opened 2017-08-10 18:11 UTC
I'm a new user to anaconda and python. I've just installed molSimplify using the following commands as per the installation instruction of HJKgrp.mit.edu/content/new-installation-option-molsimplify

conda create -n molSimplify python=2.7
source activate molSimplify
conda install -c hjkgroup molSimplify
conda install pyqt=5

It does get launched successfully but when I tried the first tutorial, the moment i click on draw ligand after selecting tpp, it crashes. The traceback for the error is as follows:

File "$HOME/Work/Softwares/anaconda2/envs/molSimplify/lib/python2.7/site-packages/molSimplify/Scripts/grabguivars.py", line 137, in writeinputf
   f = open(args['-rundir']+'/geninput.inp','w')
IOerror: [Errno 2] No such file or directory: u '$HOME/Runs//geninput.inp'
Aborted (core dumped)

I've tried it on two different computer both have ubuntu 16.04 installed as OS and conda 4.3.24 installed

Also, why is it searching in $HOME/Runs//geninput.inp? There isn't any folder like that and it makes sense that it crashed because it didn't find what it was looking for. 

Any help provided to solve this issue is much appreciated.

**Comment by jpjanet** [comment] 2017-08-11 13:49
Thanks for the heads up, we are investigating.

**Comment by jpjanet** [comment] 2017-08-11 20:46
The issue is resolved in the latest conda version. Simply run **conda -install -c hjkgroup molsimplify** to update to the latest version (1.3.5.0). The problem here was because of order of operations - running any main molSimplify function (i.e. generating a structure) for the first time on a new system automatically sets up some information about the local environment. However, running draw ligands before any structure generation has taken place was resulting in this error.

**Closed by jpjanet** 2017-08-11 20:46 UTC

**Comment by Alan-Rusty24** [comment] 2017-08-11 21:21
It works now!! Thanks for resolving it.
