### ISSUE TITLE
Tetrahedral / tetradentate ligands

### ISSUE THREAD

**Issue by ralf-meyer** [hjkgrp/molSimplify#133] opened 2023-02-17 16:32 UTC
From mail to HJK:

> I am an experimental chemist working at ETH, and I am interested in Molsimplify to speed-up the computational part of my work, and specifically get insights as described in Tutorial #12.
 > I have requested Molsimplify to be installed on our cluster and tried generating a few complexes. While I found no problem generating the structures from the tutorial and, in general, octahedral structures, I faced specific problems for tetrahedral complexes with custom ligands. I have tried several commands from the trutorial, but whatever I do, the tetradentate ligand always coordinates in a monodentate fashion to the metals that I choose. For example, for the ligand attached, the following command does not lead to the desired tetrahedral complex:
> `molsimplify -lig pdp.mol -ligocc 1 -ligcon 1,4,7,12 -skipANN True -core co -geo thd`
> I would be very grateful for any recommendations or insight regarding the generation of tetrahedral complexes. 

The main issue here is that `-ligcon` is not a valid way of specifying the connecting ligands. Resolving this issue in an email exchange has highlighted the following problems:
- defining connecting atoms for ligands loaded from files is currently not supported, i.e. `-smicat` does not work.
- the fact that the path for a custom data dir has to be provided in quotation marks is poorly documented and confusing to people.

**Comment by gianmarco-terrones** [comment] 2023-02-19 17:04
Transcript of back and forth email communication:

**HJK group**: What was the path of the .mol file on your computer when you ran that command from the terminal?

**User**: When running molsimplify, I always put the file in the directory from which I run the molsimplify command. The command runs with no errors, however, the resulting coordinate file always has the metal coordinated only to one of the nitrogen, instead of all four of them (see the .xyz attached).

**HJK group**: Unfortunately, it seems like specifying connecting atoms for ligands read from a file is currently not supported. (I have put that on our list of bugs/features for the next release) In the meantime you can construct your complex by adding the ligand to a custom ligand database (see section 3 in [tutorial 10](http://hjkgrp.mit.edu/tutorials/2018-05-09-molsimplify-tutorial-10-adding-ligands-molsimplify/) for details):

`molsimplify -ligadd pdp.mol -ligname pdp -ligcon 1,4,7,12 -skipANN True`

The first time you run this command you will be prompted to enter a path for this custom data folder which you should enter in quotation marks, e.g.: "/home/yourusername/molSimplifyData".

After adding the ligand to the database you should be able to build a complex using the name you provided for that ligand:

`molsimplify -lig pdp -ligocc 1 -skipANN True -core co -geo thd`

**User**: Whenever I try to add a custom ligand into the database, I run into problems on our cluster. The errors look like this:

```
To add to database, you need to set a custom path. Please enter a writeable file path:

path=/cluster/home/tsybizoa/molsimplify/

Traceback (most recent call last):

  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/bin/molsimplify", line 33, in <module>

    sys.exit(load_entry_point('molSimplify', 'console_scripts', 'molsimplify')())

  File "/cluster/apps/nss/gcc-6.3.0/molsimplify/1.7.1/x86_64/molSimplify/__main__.py", line 209, in main

    startgen(args, False, gui)

  File "/cluster/apps/nss/gcc-6.3.0/molsimplify/1.7.1/x86_64/molSimplify/Scripts/generator.py", line 231, in startgen

    addtoldb(smimol=args.ligadd, sminame=args.ligname, smident=len(args.ligcon),

  File "/cluster/apps/nss/gcc-6.3.0/molsimplify/1.7.1/x86_64/molSimplify/Scripts/addtodb.py", line 33, in addtoldb

    new_path = eval(input('path='))

  File "<string>", line 1

    /cluster/home/tsybizoa/molsimplify/
```
 
I am not sure whether the errors stem from the specific installation of molsimplify, the additional modules that I have loaded, or something else, perhaps you would be able to recognize, which specific problem this is caused by?

**HJK group**: Based on my experience, this probably does not have to do with additional modules you have loaded. It seems that you do not have write permission to the path that molSimplify is trying to write to, based on the error messages you are receiving. I believe you will need to have permission to write to the molSimplify/Ligands folder (this will be inside the molSimplify install on your cluster) in order to add a custom ligand to the database. You can ask someone who has root access on your cluster to enable you to do this.

As an alternative to running a command like `molsimplify -ligadd pdp.mol -ligname pdp -ligcon 1,4,7,12 -skipANN True`, you can add a geometry (xyz or mol) file for your ligand into the Ligands folder, and add a line to the ligands.dict file for your ligand. Then, you can construct your complex from the command line with a command that looks something like `molsimplify -core Ir -oxstate 3 -spin 1 -geometry oct -lig water -ligocc 6 -coord 6`, where instead of "water" you can use the name of the ligand as you have specified in the Ligands folder.

***
End result: User was able to construct desired tetrahedral complexes

**Closed** 2023-08-26 19:38 UTC
